# This is a basic workflow to help you get started with Actions

name: ReplaceSymlink

# Controls when the workflow will run
on:
  push:
    branches: 
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Download and replace symlink
        run: |
          unlink  ./extension/qoijs.min.js
          curl "https://raw.githubusercontent.com/kchapelier/qoijs/1796db56e18bfe6787b92f0b696bc0aa9e9b4566/build/qoijs.min.js" > ./extension/qoijs.min.js
      
      - uses: actions/upload-artifact@v3
        with:
          name: extension
          path: extension/
      
      - name: Comment workflow link
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            [Download extension](https://github.com/FrostBird347/qoiJS-embed/actions/runs/${{ github.run_id }})
          
